### PR TITLE
Search

### PR DESCRIPTION
**Pull request by tsye15**
Can we add this Search page

### CODE REVIEW

**Comment by tsye15** [comment]
Add text box feature

**Comment by michelleeeee** [comment]
<iframe src="//giphy.com/embed/a5C0wz8zzXdKM?html5=true" width="480" height="191" frameBorder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

**Comment by michelleeeee** [comment]
<div style="max-width: 500px;" id="_giphy_a5C0wz8zzXdKM"></div><script>var _giphy = _giphy || []; _giphy.push({id: "a5C0wz8zzXdKM",w: 500, h: 199});var g = document.createElement("script"); g.type = "text/javascript"; g.async = true;g.src = ("https:" == document.location.protocol ? "https://" : "http://") + "giphy.com/static/js/widgets/embed.js";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(g, s);</script>

**Comment by michelleeeee** [comment]
<iframe src="//giphy.com/embed/a5C0wz8zzXdKM" width="480" height="191" frameBorder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>

**Comment by michelleeeee** [comment]
@tsye15  what do you think?
th_1319836327583192

**Comment by tsye15** [comment]
Looks about right...

**Comment by tsye15** [comment]
Ok. I'm merging it in! :+1:

**Comment by michelleeeee** [comment]
giphy

**Pull request merged**
